name: Test

on:
  push:
  pull_request:

jobs:
  rush-build-test:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Setup Rush
        run: npm install -g @microsoft/rush
      - name: Install dependencies
        run: rush install

      - name: Install playwright for player testing
        run: npx playwright install --with-deps
        working-directory: packages/player

      - name: Build all packages
        run: rush build

      - name: Run tests for all Rush projects
        run: ./runTests.sh
        
